### ISSUE TITLE
Incorrect order of Indicators and Effective Weights in effectiveWeight() function

### ISSUE THREAD

**Issue by Petrina95** [bluefoxr/COINr6#1]
Hello everyone! 

First of all, thank you for this package. In the beginning of a project concerning the construction of a composite indicator, we had no idea about the package, and we didn't know how we were going to perform all the steps needed. The package seems to cover all essential steps of the COIN methodology, with really useful functions and plots. Moreover, following the easy-to-use and informative documentation, we had no issue on installing the package and run the available commands on our dataset. 

However, we encountered a small issue in the effectiveWeight() function and more specifically with the results of $EffectiveWeightsList. The file with the aggregation metadata (IndAggMeta) that we passed had no row-order in the Code column, meaning that we didn't have first the indicators, then the subareas, then the areas and lastly the index, but the order was random (1st row: Index, 2nd row: Subarea 1, 3rd row: Area1 etc.). This resulted in having inconsistencies when deriving the weights from $EffectiveWeightsList, as the Code column had the row-order of the $LabelsParents$Labels (first all indicators, then subareas, then areas and lastly the Index) and the effective weights column had the row-order of the IndAggMeta file.

We managed to overcome this issue by binding the EffWeights$LabelsParents$Labels, EffWeights$EffectiveWeights, however I think that the issue should be addressed, or in the documentation it should be specified that the order of rows in the AggMeta file is important.

Thank you in advance!

**Comment by bluefoxr** [comment]
Hi, thanks for spotting this. I have now added a fix for this, if you download the latest GitHub version it should be repaired now.

In general I'd recommend using COINr rather than COINr6, because COINr is more recent and is much more robust to bugs. You can move between the two packages using the COIN_to_coin() and coin_to_COIN() functions.

**Comment by Petrina95** [comment]
Thank you very much for your response! I will check this out!
